Repository Oglenor/RuntimeTerror, pull requests merged in 2021-03, with the labels that each got.

#11 Login component, Dummy Picture List, Navbar, Simple upload page
  src/InstagramClone/InstagramClone.Web/ClientApp/package-lock.json
  src/InstagramClone/InstagramClone.Web/ClientApp/package.json
  src/InstagramClone/InstagramClone.Web/ClientApp/src/App.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/App.test.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/assets/images/bg-hd.jpg
  src/InstagramClone/InstagramClone.Web/ClientApp/src/assets/images/logo-horizontal.png
  src/InstagramClone/InstagramClone.Web/ClientApp/src/assets/images/logo.png
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Counter.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Home.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Home/Home.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Home/Home.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Layout/Layout.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Layout/Layout.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Login/Login.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Login/Login.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/NavMenu.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Upload/Upload.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Upload/Upload.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/index.js
Labels: Frontend

#10 Image upload
  src/InstagramClone/InstagramClone.Web/Controllers/ImageController.cs
  src/InstagramClone/InstagramClone.Web/InstagramClone.Web.csproj
  src/InstagramClone/InstagramClone.Web/Models/Image.cs
  src/InstagramClone/InstagramClone.Web/Models/ImageDTO.cs
  src/InstagramClone/InstagramClone.Web/Startup.cs
Labels: Backend

#14 Upload Component
  src/InstagramClone/.idea/workspace.xml
  src/InstagramClone/InstagramClone.Web/ClientApp/package-lock.json
  src/InstagramClone/InstagramClone.Web/ClientApp/package.json
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Layout/Layout.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Upload/Upload.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Upload/Upload.js
Labels: Frontend

#15 Update navbar component
  src/InstagramClone/.idea/workspace.xml
  src/InstagramClone/InstagramClone.Web/ClientApp/package-lock.json
  src/InstagramClone/InstagramClone.Web/ClientApp/package.json
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/NavMenu.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/NavMenu.js
Labels: Frontend

#22 Connect API enpoint to Frontend and some minor changes
  .gitignore
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Home/Home.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Layout/Layout.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/NavBar/NavMenu.css
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/NavBar/NavMenu.js
  src/InstagramClone/InstagramClone.Web/ClientApp/src/components/Upload/Upload.js
  src/InstagramClone/InstagramClone.Web/Controllers/ImageController.cs
Labels: Backend, Frontend
